# Docker compose file to start postgres together with keycloak
version: '2'
services:
  mariadb:
    image: mariadb:latest
    container_name: "keycloak-testready-mariadb"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
      - MYSQL_ROOT_PASSWORD=${dbRootPw}
      - MYSQL_INITDB_SKIP_TZINFO=1
  keycloak:
    image: fuinorg/keycloak-testready:1.2.0-SNAPSHOT
    container_name: "keycloak-testready-keycloak"
    ports:
      - "8088:8080"
    environment:
      - WAIT_FOR_DB=true
      - WAIT_FOR_SECONDS=30
      - DB_VENDOR=MYSQL
      - DB_ADDR=mariadb
      - DB_PORT=3306
      - DB_DATABASE=${dbName}
      - DB_USER=${dbUser}
      - DB_PASSWORD=${dbPassword}
      - KEYCLOAK_USER=${keycloakUser}
      - KEYCLOAK_PASSWORD=${keycloakPassword}
      - "IMPORT_JSON={\"realm\":\"tst\",\"enabled\":true,\"requiredCredentials\":[\"password\"],\"roles\":{\"realm\":[{\"name\":\"user\",\"description\":\"User privileges\"},{\"name\":\"admin\",\"description\":\"Administrator privileges\"}]},\"users\":[{\"username\":\"peter\",\"enabled\":true,\"credentials\":[{\"type\":\"password\",\"value\":\"abc\"}],\"realmRoles\":[\"admin\"]},{\"username\":\"john\",\"enabled\":true,\"credentials\":[{\"type\":\"password\",\"value\":\"abc\"}],\"realmRoles\":[\"user\"]}],\"clients\":[{\"clientId\":\"my-service\",\"bearerOnly\":true},{\"clientId\":\"test\",\"bearerOnly\":false,\"standardFlowEnabled\":false,\"implicitFlowEnabled\":false,\"directAccessGrantsEnabled\":true,\"publicClient\":true,\"redirectUris\":[\"http://localhost\"]}]}"
    depends_on:
      - mariadb      
 